### PR TITLE
Add basic structure of the project

### PR DESCRIPTION
**Pull request by thirdmadman**
This is syncup PR, mostyly for codereview.

### CODE REVIEW

**Comment by DianaSmertina** [comment]
Привет! мне кажется, по структуре и стилю кода все хорошо, есть предложение вынести цвета и размеры экранов в переменные (для медиа запросов), чтобы легче их использовать и при желании везде поменять. У меня есть кусочек с цветами
```
$color_basic: #F6F6F6;
$color_interactions: #263C93;
$color_balanced: #E38895;
$color_dark: #282828;
$color_smiled: #FFDB23;
$color_secondary-text: #8B8B8B;
```

**Comment by thirdmadman** [comment]
Could we please communicate in english?

Yeah, I agree, scss variables will be good addition.

@DianaSmertina, I suggest using this:

``` scss
$color-light-xl: #FFFFFF;
$color-dark-l: #F9F9F9;
$color-light-m: #F6F6F6;
$color-light-s: #E0E0E0;
$color-dark-m: #8B8B8B;
$color-dark-l: #282828;

$color-primary-yellow: #FFDB23;
$color-primary-blue: #263C93;
$color-primary-pink: #E38895;
```

**Comment by thirdmadman** [comment]
For layout breakpoints we could use:

``` scss
$layout-breakpoint-desktop-xl: 1920px;
$layout-breakpoint-desktop-l: 1760px;
$layout-breakpoint-desktop-m: 1600px;
$layout-breakpoint-desktop-s: 1490px;
$layout-breakpoint-desktop-xs: 1280px;

$layout-breakpoint-mobile-xl: 1167px;
$layout-breakpoint-desktop-l: 1000px;
$layout-breakpoint-desktop-m: 910px;
$layout-breakpoint-desktop-s: 774px;
$layout-breakpoint-desktop-xs: 428px;
$layout-breakpoint-desktop-xxs: 390px;
```

**Comment by DianaSmertina** [comment]
> For layout breakpoints we could use:
> 
> ```css-scss
> $layout-breakpoint-desktop-xl: 1920px;
> $layout-breakpoint-desktop-l: 1760px;
> $layout-breakpoint-desktop-m: 1600px;
> $layout-breakpoint-desktop-s: 1490px;
> $layout-breakpoint-desktop-xs: 1280px;
> 
> $layout-breakpoint-mobile-xl: 1167px;
> $layout-breakpoint-mobile-l: 1000px;
> $layout-breakpoint-mobile-m: 910px;
> $layout-breakpoint-mobile-s: 774px;
> $layout-breakpoint-mobile-xs: 428px;
> $layout-breakpoint-mobile-xxs: 390px;
> ```

Maybe fix big mobile screens on tablet? because there are no such big phones and looks a little bit strange 
```
$layout-breakpoint-tablet-l: 1167px;
$layout-breakpoint-tablet-m 1000px;
$layout-breakpoint-tablet-s: 910px;
$layout-breakpoint-tablet-xs: 774px;
$layout-breakpoint-mobile-m: 428px;
$layout-breakpoint-mobile-s: 390px;
```

**Comment by thirdmadman** [comment]
> > For layout breakpoints we could use:
> > ```
> > $layout-breakpoint-desktop-xl: 1920px;
> > $layout-breakpoint-desktop-l: 1760px;
> > $layout-breakpoint-desktop-m: 1600px;
> > $layout-breakpoint-desktop-s: 1490px;
> > $layout-breakpoint-desktop-xs: 1280px;
> > 
> > $layout-breakpoint-mobile-xl: 1167px;
> > $layout-breakpoint-mobile-l: 1000px;
> > $layout-breakpoint-mobile-m: 910px;
> > $layout-breakpoint-mobile-s: 774px;
> > $layout-breakpoint-mobile-xs: 428px;
> > $layout-breakpoint-mobile-xxs: 390px;
> > ```
> 
> Maybe fix big mobile screens on tablet? because there are no such big phones and looks a little bit strange
> 
> ```
> $layout-breakpoint-tablet-l: 1167px;
> $layout-breakpoint-tablet-m: 1000px;
> $layout-breakpoint-tablet-s: 910px;
> $layout-breakpoint-tablet-xs: 774px;
> $layout-breakpoint-mobile-m: 428px;
> $layout-breakpoint-mobile-s: 390px;
> ```

Yeah, it seems like I missed out on information when I was researching screen resolutions on Apple phones.

Tablet fit better in this context.

**Review by DianaSmertina — APPROVED** [review]

**Pull request merged**
